/**
 * Report generation service for clinical records export
 */
class ReportService {
  /**
   * Format text report for an individual wound entry
   */
  generateEntryReport(entry, user) {
    const assessmentDetails = typeof entry.assessment_details === 'string'
      ? JSON.parse(entry.assessment_details)
      : (entry.assessment_details || {});

    const dateFormatted = new Date(entry.entry_date || entry.created_at).toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });

    return `
===============================================================
               WOUNDWISE CLINICAL LOG REPORT
===============================================================

PATIENT INFORMATION
---------------------------------------------------------------
Patient Name   : ${user.name}
Patient Email  : ${user.email}
Report Date    : ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

WOUND RECORD DETAILS
---------------------------------------------------------------
Record ID      : ${entry.id}
Wound Case     : ${entry.wound_title}
Anatomic Site  : ${entry.wound_location}
Entry Type     : ${entry.is_followup ? 'Follow-up Tracking Photo' : 'Initial Baseline Photo'}
Captured On    : ${dateFormatted}
Status         : ${entry.wound_status || 'Active'}

PATIENT NOTES
---------------------------------------------------------------
${entry.notes || 'No user notes entered.'}

ASSESSMENT STATUS
---------------------------------------------------------------
Assessment     : ${entry.assessment_summary || 'Analysis not configured'}
System Status  : ${entry.assessment_status || 'not_configured'}
Details        : ${assessmentDetails.statusMessage || assessmentDetails.clinicalNote || 'Clinical wound documentation recorded securely.'}

DISCLAIMER
---------------------------------------------------------------
WoundWise is an electronic documentation and tracking tool. This
document does not constitute a definitive medical diagnosis or
clinical prescription. If you experience worsening pain, fever,
spreading redness, or unusual discharge, consult your healthcare
provider immediately.

===============================================================
Generated by WoundWise Health Platform · https://woundwise.app
===============================================================
    `.trim();
  }
}

module.exports = new ReportService();
